kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: mineralcatalog
  namespace: default
  labels:
    app: mineralcatalog
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: mineralcatalog
    spec:
      volumes:
        - name: configs
          configMap:
            name: mineralcatalog
      containers:
        - name: mineralcatalog
          image: gcr.io/mineral-catalog-225400/mineral-catalog:v0.0.2-0
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: configs
              mountPath: /configs
          env:
            - name: mineralcatalog_configfile
              value: /configs/mineralcatalog.json
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /configs/gcloud.json
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 80
              scheme: HTTP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 80
              scheme: HTTP
