kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata:
  name: mineralcatalog
  namespace: default
  labels:
    app: mineralcatalog
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: mineralcatalog
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
