kind: Service
apiVersion: v1
metadata:
  name: mineralcatalog
  labels:
    app: mineralcatalog
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mineralcatalog
